spring:
  # 数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.97:15432/cloud?options=-c%20TimeZone=Asia/Shanghai
    username: cloud
    password: CloudDev
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  security:
    whitelist:
      - /articles/query
      - /articles/all
      - /articles/get/*
      - /articles/views/*
      - /articles/category/*
      - /articles/author/*
      - /articles/search
      - /ai/generate-summary
      - /ai/chat
      - /ai/health-check
      - /ai/health

# AI配置
google:
  ai:
    api-key: AIzaSyCUHFwrJmFS0jnN7FUsHft7K39FjMkI34U
    model: gemini-2.5-flash
